tap "aws/tap"
tap "dbcli/tap"
tap "homebrew/bundle"
tap "homebrew/core"
# tap "linuxbrew/xorg"
brew "act"
brew "bat"
brew "broot"
brew "curl"
brew "ctop"
brew "docker"
brew "docker-compose"
brew "duf"
brew "dust"
brew "exa"
brew "fd"
brew "fzf"
brew "git"
brew "git-delta"
brew "htop"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "litecli"
brew "make"
brew "mas"
brew "node"
brew "procs"
brew "ripgrep"
brew "sd"
brew "starship"
brew "tmux"
brew "tldr"
brew "vim"
brew "zsh"
brew "zsh-completions"
brew "cantino/mcfly/mcfly"

cask "alfred"
cask "biscuit"
cask "clipy"
cask "drawio"
cask "kindle"
cask "github"
cask "google-chrome"
cask "google-japanese-ime"
cask "microsoft-office"
cask "slack"
cask "spotify"
cask "visual-studio-code"

mas "LINE", id: 539883307
mas "TweetDeck", id: 485812721
mas "Xcode", id: 497799835
