#!/usr/bin/env bash
# -*- coding: utf-8 -*-

set -e

# @describe Setup environment and tools

# @cmd setup environments and tools
setup() {
	:
}

# @cmd unset environments and tools
clean() {
	:
}

# @cmd setup devbox
setup::devbox() {
	# devboxがインストールされていない場合はインストールする
	if ! command -v devbox 2>&1 >/dev/null; then
		curl -fsSL https://get.jetify.com/devbox | bash -s -- -f
	else
		echo "devbox is already installed"
	fi

	if ! (command -v git 2>&1 >/dev/null && command -v xz 2>&1 >/dev/null); then
		echo "git or xz are not found. install them."
		exit 1
	fi

	# need curl, git, xz
	# apt update
	# apt install curl git xz-utils
	yes | devbox global pull https://github.com/Nishikoh/devbox.git
	eval "$(devbox global shellenv)"
}

# @cmd setup rust and cargo
setup::rust() {
	:
}

# @cmd setup rust and cargo
# @meta default-subcommand
setup::rust::install() {
	# rustがインストールされていない場合はインストールする
	if ! command -v cargo 2>&1 >/dev/null; then
		curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
	else
		echo "rust is already installed"
	fi
}

# @cmd install cargo binary. need some time.
setup::rust::bins() {
	setup::rust::install
	cargo install cargo-binstall
	cargo binstall cpz
	cargo binstall rmz
	cargo binstall xcp
}

# @cmd setup github copilot
# @alias gh-copilot
setup::copilot() {

	if ! gh copilot --version; then
		gh auth login --web -h github.com
		gh extension install github/gh-copilot --force
	fi

	echo "Start Vim/Neovim and invoke :Copilot setup."
	git clone https://github.com/github/copilot.vim.git \
		~/.vim/pack/github/start/copilot.vim
}

# @cmd setup cuda
setup::cuda() {
	echo "TODO:"
	# TODO: setup CUDA
	# disable auto upgrade
}

# @cmd
# @meta default-subcommand
setup::cuda::install() {
	echo "TODO: install CUDA"
}

link_targets_list=(".gitconfig" ".vimrc" ".zshrc")

# @cmd setup dotfiles
# @arg path=~/dev/dotfiles 		path to git clone
setup::dotfiles() {

	if [ "$argc_path" = "$HOME" ]; then
		echo invalid dir. This is Home.
		exit 1
	fi

	if [ -d "$argc_path" ]; then
		echo "skip git clone"
	else
		git clone https://github.com/Nishikoh/dotfiles.git ${argc_path}
	fi

	ORIGINAL_DOTFILES_PATH=$( (cd "${argc_path}" && pwd))
	ZSH_CONFIG_DIR=$ORIGINAL_DOTFILES_PATH/zsh

	if [ -d "$ZSH_CONFIG_DIR" ]; then
		ls "$ZSH_CONFIG_DIR"
	else
		echo zsh dir is not exists.
		exit 1
	fi

	for f in "${link_targets_list[@]}"; do
		if [[ -e "${ORIGINAL_DOTFILES_PATH}/${f}" ]]; then
			if [[ ! -e "${HOME}/${f}" ]] || diff -u "${ORIGINAL_DOTFILES_PATH}/${f}" "${HOME}/${f}"; then
				ln -snfv "${ORIGINAL_DOTFILES_PATH}/${f}" "${HOME}/${f}"
				echo link: "${f}"
			fi
		fi
	done
}

# @cmd unset dotfiles
clean::dotfiles() {
	for f in "${link_targets_list[@]}"; do
		if [ -L ~/"${f}" ]; then
			echo "$f"
			unlink ~/"${f}"
		fi
	done
}

# @cmd completion shell
# @arg path=~/dev/dotfiles 		path to git clone
setup::completion() {
	setup::dotfiles $argc_path
	git clone https://github.com/sigoden/argc-completions.git
	cd argc-completions
	./scripts/download-tools.sh
	./scripts/setup-shell.sh zsh
	cd -
}

# @cmd setup environments and tools quickly.
# @arg path=~/dev/dotfiles 		path to git clone
setup::slim() {
	setup::devbox
	setup::dotfiles $argc_path
	setup::completion $argc_path
	setup::copilot
}

# @cmd setup full environments and tools. need some time.
# @arg path=~/dev/dotfiles 		path to git clone
setup::full() {
	setup::slim $argc_path
	setup::rust::bins
}

# See more details at https://github.com/sigoden/argc
# ARGC-BUILD {
# This block was generated by argc (https://github.com/sigoden/argc).
# Modifying it manually is not recommended

_argc_run() {
    if [[ "${1:-}" == "___internal___" ]]; then
        _argc_die "error: unsupported ___internal___ command"
    fi
    if [[ "${OS:-}" == "Windows_NT" ]] && [[ -n "${MSYSTEM:-}" ]]; then
        set -o igncr
    fi
    argc__args=("$(basename "$0" .sh)" "$@")
    argc__positionals=()
    _argc_index=1
    _argc_len="${#argc__args[@]}"
    _argc_tools=()
    _argc_parse
    if [ -n "${argc__fn:-}" ]; then
        $argc__fn "${argc__positionals[@]}"
    fi
}

_argc_usage() {
    cat <<-'EOF'
Setup environment and tools

USAGE: Argcfile <COMMAND>

COMMANDS:
  setup  setup environments and tools
  clean  unset environments and tools
EOF
    exit
}

_argc_version() {
    echo Argcfile 0.0.0
    exit
}

_argc_parse() {
    local _argc_key _argc_action
    local _argc_subcmds="setup, clean"
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage
            ;;
        --version | -version | -V)
            _argc_version
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        setup)
            _argc_index=$((_argc_index + 1))
            _argc_action=_argc_parse_setup
            break
            ;;
        clean)
            _argc_index=$((_argc_index + 1))
            _argc_action=_argc_parse_clean
            break
            ;;
        help)
            local help_arg="${argc__args[$((_argc_index + 1))]:-}"
            case "$help_arg" in
            setup)
                _argc_usage_setup
                ;;
            clean)
                _argc_usage_clean
                ;;
            "")
                _argc_usage
                ;;
            *)
                _argc_die "error: invalid value \`$help_arg\` for \`<command>\`"$'\n'"  [possible values: $_argc_subcmds]"
                ;;
            esac
            ;;
        *)
            _argc_die "error: \`Argcfile\` requires a subcommand but one was not provided"$'\n'"  [subcommands: $_argc_subcmds]"
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        _argc_usage
    fi
}

_argc_usage_setup() {
    cat <<-'EOF'
setup environments and tools

USAGE: Argcfile setup <COMMAND>

COMMANDS:
  devbox      setup devbox
  rust        setup rust and cargo
  copilot     setup github copilot [aliases: gh-copilot]
  cuda        setup cuda
  dotfiles    setup dotfiles
  completion  completion shell
  slim        setup environments and tools quickly.
  full        setup full environments and tools. need some time.
EOF
    exit
}

_argc_parse_setup() {
    local _argc_key _argc_action
    local _argc_subcmds="devbox, rust, copilot, gh-copilot, cuda, dotfiles, completion, slim, full"
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage_setup
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        devbox)
            _argc_index=$((_argc_index + 1))
            _argc_action=_argc_parse_setup_devbox
            break
            ;;
        rust)
            _argc_index=$((_argc_index + 1))
            _argc_action=_argc_parse_setup_rust
            break
            ;;
        copilot | gh-copilot)
            _argc_index=$((_argc_index + 1))
            _argc_action=_argc_parse_setup_copilot
            break
            ;;
        cuda)
            _argc_index=$((_argc_index + 1))
            _argc_action=_argc_parse_setup_cuda
            break
            ;;
        dotfiles)
            _argc_index=$((_argc_index + 1))
            _argc_action=_argc_parse_setup_dotfiles
            break
            ;;
        completion)
            _argc_index=$((_argc_index + 1))
            _argc_action=_argc_parse_setup_completion
            break
            ;;
        slim)
            _argc_index=$((_argc_index + 1))
            _argc_action=_argc_parse_setup_slim
            break
            ;;
        full)
            _argc_index=$((_argc_index + 1))
            _argc_action=_argc_parse_setup_full
            break
            ;;
        help)
            local help_arg="${argc__args[$((_argc_index + 1))]:-}"
            case "$help_arg" in
            devbox)
                _argc_usage_setup_devbox
                ;;
            rust)
                _argc_usage_setup_rust
                ;;
            copilot | gh-copilot)
                _argc_usage_setup_copilot
                ;;
            cuda)
                _argc_usage_setup_cuda
                ;;
            dotfiles)
                _argc_usage_setup_dotfiles
                ;;
            completion)
                _argc_usage_setup_completion
                ;;
            slim)
                _argc_usage_setup_slim
                ;;
            full)
                _argc_usage_setup_full
                ;;
            "")
                _argc_usage_setup
                ;;
            *)
                _argc_die "error: invalid value \`$help_arg\` for \`<command>\`"$'\n'"  [possible values: $_argc_subcmds]"
                ;;
            esac
            ;;
        *)
            _argc_die "error: \`Argcfile-setup\` requires a subcommand but one was not provided"$'\n'"  [subcommands: $_argc_subcmds]"
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        _argc_usage_setup
    fi
}

_argc_usage_setup_devbox() {
    cat <<-'EOF'
setup devbox

USAGE: Argcfile setup devbox
EOF
    exit
}

_argc_parse_setup_devbox() {
    local _argc_key _argc_action
    local _argc_subcmds=""
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage_setup_devbox
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        *)
            argc__positionals+=("$_argc_item")
            _argc_index=$((_argc_index + 1))
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        argc__fn=setup::devbox
        if [[ "${argc__positionals[0]:-}" == "help" ]] && [[ "${#argc__positionals[@]}" -eq 1 ]]; then
            _argc_usage_setup_devbox
        fi
    fi
}

_argc_usage_setup_rust() {
    cat <<-'EOF'
setup rust and cargo

USAGE: Argcfile setup rust <COMMAND>

COMMANDS:
  install  setup rust and cargo [default]
  bins     install cargo binary. need some time.
EOF
    exit
}

_argc_parse_setup_rust() {
    local _argc_key _argc_action
    local _argc_subcmds="install, bins"
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage_setup_rust
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        install)
            _argc_index=$((_argc_index + 1))
            _argc_action=_argc_parse_setup_rust_install
            break
            ;;
        bins)
            _argc_index=$((_argc_index + 1))
            _argc_action=_argc_parse_setup_rust_bins
            break
            ;;
        help)
            local help_arg="${argc__args[$((_argc_index + 1))]:-}"
            case "$help_arg" in
            install)
                _argc_usage_setup_rust_install
                ;;
            bins)
                _argc_usage_setup_rust_bins
                ;;
            "")
                _argc_usage_setup_rust
                ;;
            *)
                _argc_die "error: invalid value \`$help_arg\` for \`<command>\`"$'\n'"  [possible values: $_argc_subcmds]"
                ;;
            esac
            ;;
        *)
            if [[ "${#argc__positionals[@]}" -eq 0 ]]; then
                _argc_action=_argc_parse_setup_rust_install
                break
            fi
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        _argc_usage_setup_rust
    fi
}

_argc_usage_setup_rust_install() {
    cat <<-'EOF'
setup rust and cargo

USAGE: Argcfile setup rust install
EOF
    exit
}

_argc_parse_setup_rust_install() {
    local _argc_key _argc_action
    local _argc_subcmds=""
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage_setup_rust_install
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        *)
            argc__positionals+=("$_argc_item")
            _argc_index=$((_argc_index + 1))
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        argc__fn=setup::rust::install
        if [[ "${argc__positionals[0]:-}" == "help" ]] && [[ "${#argc__positionals[@]}" -eq 1 ]]; then
            _argc_usage_setup_rust_install
        fi
    fi
}

_argc_usage_setup_rust_bins() {
    cat <<-'EOF'
install cargo binary. need some time.

USAGE: Argcfile setup rust bins
EOF
    exit
}

_argc_parse_setup_rust_bins() {
    local _argc_key _argc_action
    local _argc_subcmds=""
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage_setup_rust_bins
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        *)
            argc__positionals+=("$_argc_item")
            _argc_index=$((_argc_index + 1))
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        argc__fn=setup::rust::bins
        if [[ "${argc__positionals[0]:-}" == "help" ]] && [[ "${#argc__positionals[@]}" -eq 1 ]]; then
            _argc_usage_setup_rust_bins
        fi
    fi
}

_argc_usage_setup_copilot() {
    cat <<-'EOF'
setup github copilot

USAGE: Argcfile setup copilot
EOF
    exit
}

_argc_parse_setup_copilot() {
    local _argc_key _argc_action
    local _argc_subcmds=""
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage_setup_copilot
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        *)
            argc__positionals+=("$_argc_item")
            _argc_index=$((_argc_index + 1))
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        argc__fn=setup::copilot
        if [[ "${argc__positionals[0]:-}" == "help" ]] && [[ "${#argc__positionals[@]}" -eq 1 ]]; then
            _argc_usage_setup_copilot
        fi
    fi
}

_argc_usage_setup_cuda() {
    cat <<-'EOF'
setup cuda

USAGE: Argcfile setup cuda <COMMAND>

COMMANDS:
  install  [default]
EOF
    exit
}

_argc_parse_setup_cuda() {
    local _argc_key _argc_action
    local _argc_subcmds="install"
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage_setup_cuda
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        install)
            _argc_index=$((_argc_index + 1))
            _argc_action=_argc_parse_setup_cuda_install
            break
            ;;
        help)
            local help_arg="${argc__args[$((_argc_index + 1))]:-}"
            case "$help_arg" in
            install)
                _argc_usage_setup_cuda_install
                ;;
            "")
                _argc_usage_setup_cuda
                ;;
            *)
                _argc_die "error: invalid value \`$help_arg\` for \`<command>\`"$'\n'"  [possible values: $_argc_subcmds]"
                ;;
            esac
            ;;
        *)
            if [[ "${#argc__positionals[@]}" -eq 0 ]]; then
                _argc_action=_argc_parse_setup_cuda_install
                break
            fi
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        _argc_usage_setup_cuda
    fi
}

_argc_usage_setup_cuda_install() {
    cat <<-'EOF'
USAGE: Argcfile setup cuda install
EOF
    exit
}

_argc_parse_setup_cuda_install() {
    local _argc_key _argc_action
    local _argc_subcmds=""
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage_setup_cuda_install
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        *)
            argc__positionals+=("$_argc_item")
            _argc_index=$((_argc_index + 1))
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        argc__fn=setup::cuda::install
        if [[ "${argc__positionals[0]:-}" == "help" ]] && [[ "${#argc__positionals[@]}" -eq 1 ]]; then
            _argc_usage_setup_cuda_install
        fi
    fi
}

_argc_usage_setup_dotfiles() {
    cat <<-'EOF'
setup dotfiles

USAGE: Argcfile setup dotfiles [PATH]

ARGS:
  [PATH]  path to git clone [default: ~/dev/dotfiles]
EOF
    exit
}

_argc_parse_setup_dotfiles() {
    local _argc_key _argc_action
    local _argc_subcmds=""
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage_setup_dotfiles
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        *)
            argc__positionals+=("$_argc_item")
            _argc_index=$((_argc_index + 1))
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        argc__fn=setup::dotfiles
        if [[ "${argc__positionals[0]:-}" == "help" ]] && [[ "${#argc__positionals[@]}" -eq 1 ]]; then
            _argc_usage_setup_dotfiles
        fi
        _argc_match_positionals 0
        local values_index values_size
        IFS=: read -r values_index values_size <<<"${_argc_match_positionals_values[0]:-}"
        if [[ -n "$values_index" ]]; then
            argc_path="${argc__positionals[values_index]}"
        else
            argc_path=~/dev/dotfiles
            argc__positionals+=("$argc_path")
        fi
    fi
}

_argc_usage_setup_completion() {
    cat <<-'EOF'
completion shell

USAGE: Argcfile setup completion [PATH]

ARGS:
  [PATH]  path to git clone [default: ~/dev/dotfiles]
EOF
    exit
}

_argc_parse_setup_completion() {
    local _argc_key _argc_action
    local _argc_subcmds=""
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage_setup_completion
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        *)
            argc__positionals+=("$_argc_item")
            _argc_index=$((_argc_index + 1))
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        argc__fn=setup::completion
        if [[ "${argc__positionals[0]:-}" == "help" ]] && [[ "${#argc__positionals[@]}" -eq 1 ]]; then
            _argc_usage_setup_completion
        fi
        _argc_match_positionals 0
        local values_index values_size
        IFS=: read -r values_index values_size <<<"${_argc_match_positionals_values[0]:-}"
        if [[ -n "$values_index" ]]; then
            argc_path="${argc__positionals[values_index]}"
        else
            argc_path=~/dev/dotfiles
            argc__positionals+=("$argc_path")
        fi
    fi
}

_argc_usage_setup_slim() {
    cat <<-'EOF'
setup environments and tools quickly.

USAGE: Argcfile setup slim [PATH]

ARGS:
  [PATH]  path to git clone [default: ~/dev/dotfiles]
EOF
    exit
}

_argc_parse_setup_slim() {
    local _argc_key _argc_action
    local _argc_subcmds=""
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage_setup_slim
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        *)
            argc__positionals+=("$_argc_item")
            _argc_index=$((_argc_index + 1))
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        argc__fn=setup::slim
        if [[ "${argc__positionals[0]:-}" == "help" ]] && [[ "${#argc__positionals[@]}" -eq 1 ]]; then
            _argc_usage_setup_slim
        fi
        _argc_match_positionals 0
        local values_index values_size
        IFS=: read -r values_index values_size <<<"${_argc_match_positionals_values[0]:-}"
        if [[ -n "$values_index" ]]; then
            argc_path="${argc__positionals[values_index]}"
        else
            argc_path=~/dev/dotfiles
            argc__positionals+=("$argc_path")
        fi
    fi
}

_argc_usage_setup_full() {
    cat <<-'EOF'
setup full environments and tools. need some time.

USAGE: Argcfile setup full [PATH]

ARGS:
  [PATH]  path to git clone [default: ~/dev/dotfiles]
EOF
    exit
}

_argc_parse_setup_full() {
    local _argc_key _argc_action
    local _argc_subcmds=""
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage_setup_full
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        *)
            argc__positionals+=("$_argc_item")
            _argc_index=$((_argc_index + 1))
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        argc__fn=setup::full
        if [[ "${argc__positionals[0]:-}" == "help" ]] && [[ "${#argc__positionals[@]}" -eq 1 ]]; then
            _argc_usage_setup_full
        fi
        _argc_match_positionals 0
        local values_index values_size
        IFS=: read -r values_index values_size <<<"${_argc_match_positionals_values[0]:-}"
        if [[ -n "$values_index" ]]; then
            argc_path="${argc__positionals[values_index]}"
        else
            argc_path=~/dev/dotfiles
            argc__positionals+=("$argc_path")
        fi
    fi
}

_argc_usage_clean() {
    cat <<-'EOF'
unset environments and tools

USAGE: Argcfile clean <COMMAND>

COMMANDS:
  dotfiles  unset dotfiles
EOF
    exit
}

_argc_parse_clean() {
    local _argc_key _argc_action
    local _argc_subcmds="dotfiles"
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage_clean
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        dotfiles)
            _argc_index=$((_argc_index + 1))
            _argc_action=_argc_parse_clean_dotfiles
            break
            ;;
        help)
            local help_arg="${argc__args[$((_argc_index + 1))]:-}"
            case "$help_arg" in
            dotfiles)
                _argc_usage_clean_dotfiles
                ;;
            "")
                _argc_usage_clean
                ;;
            *)
                _argc_die "error: invalid value \`$help_arg\` for \`<command>\`"$'\n'"  [possible values: $_argc_subcmds]"
                ;;
            esac
            ;;
        *)
            _argc_die "error: \`Argcfile-clean\` requires a subcommand but one was not provided"$'\n'"  [subcommands: $_argc_subcmds]"
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        _argc_usage_clean
    fi
}

_argc_usage_clean_dotfiles() {
    cat <<-'EOF'
unset dotfiles

USAGE: Argcfile clean dotfiles
EOF
    exit
}

_argc_parse_clean_dotfiles() {
    local _argc_key _argc_action
    local _argc_subcmds=""
    while [[ $_argc_index -lt $_argc_len ]]; do
        _argc_item="${argc__args[_argc_index]}"
        _argc_key="${_argc_item%%=*}"
        case "$_argc_key" in
        --help | -help | -h)
            _argc_usage_clean_dotfiles
            ;;
        --)
            _argc_dash="${#argc__positionals[@]}"
            argc__positionals+=("${argc__args[@]:$((_argc_index + 1))}")
            _argc_index=$_argc_len
            break
            ;;
        *)
            argc__positionals+=("$_argc_item")
            _argc_index=$((_argc_index + 1))
            ;;
        esac
    done
    if [[ -n "${_argc_action:-}" ]]; then
        $_argc_action
    else
        argc__fn=clean::dotfiles
        if [[ "${argc__positionals[0]:-}" == "help" ]] && [[ "${#argc__positionals[@]}" -eq 1 ]]; then
            _argc_usage_clean_dotfiles
        fi
    fi
}

_argc_match_positionals() {
    _argc_match_positionals_values=()
    _argc_match_positionals_len=0
    local params=("$@")
    local args_len="${#argc__positionals[@]}"
    if [[ $args_len -eq 0 ]]; then
        return
    fi
    local params_len=$# arg_index=0 param_index=0
    while [[ $param_index -lt $params_len && $arg_index -lt $args_len ]]; do
        local takes=0
        if [[ "${params[param_index]}" -eq 1 ]]; then
            if [[ $param_index -eq 0 ]] &&
                [[ ${_argc_dash:-} -gt 0 ]] &&
                [[ $params_len -eq 2 ]] &&
                [[ "${params[$((param_index + 1))]}" -eq 1 ]] \
                ; then
                takes=${_argc_dash:-}
            else
                local arg_diff=$((args_len - arg_index)) param_diff=$((params_len - param_index))
                if [[ $arg_diff -gt $param_diff ]]; then
                    takes=$((arg_diff - param_diff + 1))
                else
                    takes=1
                fi
            fi
        else
            takes=1
        fi
        _argc_match_positionals_values+=("$arg_index:$takes")
        arg_index=$((arg_index + takes))
        param_index=$((param_index + 1))
    done
    if [[ $arg_index -lt $args_len ]]; then
        _argc_match_positionals_values+=("$arg_index:$((args_len - arg_index))")
    fi
    _argc_match_positionals_len=${#_argc_match_positionals_values[@]}
    if [[ $params_len -gt 0 ]] && [[ $_argc_match_positionals_len -gt $params_len ]]; then
        local index="${_argc_match_positionals_values[params_len]%%:*}"
        _argc_die "error: unexpected argument \`${argc__positionals[index]}\` found"
    fi
}

_argc_die() {
    if [[ $# -eq 0 ]]; then
        cat
    else
        echo "$*" >&2
    fi
    exit 1
}

_argc_run "$@"

# ARGC-BUILD }
