# TODO:
# https://docs.astral.sh/ruff/configuration/#configuring-ruff
# https://docs.astral.sh/ruff/rules/

# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist/",
  "node_modules",
  "site-packages",
  "venv",
]

# Same as Black.
line-length = 100
indent-width = 4

target-version = "py310"

[lint]
select = [
  "ALL",
  "F",
  "E",
  "W",
  "C90",
  "I",
  "N",
  "UP",
  "ANN", # 厳しければ除外
  "ASYNC",
  "S",
  "FBT",
  "B",
  "A",
  "COM",
  "C4",
  "DTZ",
  "LOG",
  "G",
  "PIE",
  "T20",
  "PT",
  "Q",
  "RET",
  "SIM",
  "TC",
  "ARG",
  "PTH",
  "ERA",
  "PD",
  "PGH",
  "PL",
  "E",
  "R",
  "W",
  "TRY",
  "NPY",
  "FAST",
  "PERF",
  "FURB",
  "RUF",
]
ignore = [
  "E501",
  #"RUF100",
  #"ERA001",
  "D",
  "TRY003",
  "INP",
  #"ANN",
  "TD",
  "FIX",
]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[lint.pylint]
max-returns = 2
max-statements = 20
max-branches = 5
max-args = 5

[lint.mccabe]
max-complexity = 7

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
