# theme = "catppuccin_macchiato"
# theme = "sonokai"
# thtme = "pop-dark"
# theme = "catppuccin_frappe"
theme = "my-theme"


[editor]
true-color = true

[keys.normal]
y = ["yank", ":clipboard-yank"]
C-y = [
	':sh rm -f /tmp/unique-ca1ea106',
	':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-ca1ea106',
	':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
	':open %sh{cat /tmp/unique-ca1ea106}',
	':redraw',
	':set mouse false',
  ':set mouse true',
]

[editor.file-picker]
hidden = false
git-ignore = false
git-global = false
git-exclude = false

[editor.cursor-shape]
insert = "bar" # 日本語入力で表示がおかしくならない設定

[editor.soft-wrap]
enable = true
max-wrap = 20
max-indent-retain = 40
# wrap-indicator = "|>|> "

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "hint" # エラーメッセージなどをインラインにする

[editor.statusline]
center = ["file-type"]
