theme = "catppuccin_macchiato"

[editor]
true-color = true

[keys.normal]
y = ["yank", ":clipboard-yank"]   
C-y = ":sh zellij run -n Yazi -c -f -x 5%% -y 10%% --width 90%% --height 90%% -- bash ~/.config/helix/yazi-picker.sh"

[editor.file-picker]
hidden = false
git-ignore = false
git-global = false
git-exclude = false

[editor.cursor-shape]
insert = "bar" # 日本語入力で表示がおかしくならない設定

[editor.soft-wrap]
enable = true
max-wrap = 20
max-indent-retain = 40
# wrap-indicator = "|>|> " 
