[language-server.copilot]
command = "npx"
args = ["@github/copilot-language-server", "--stdio"]

[[language]]
name = "python"
language-servers = ["ty","ruff","copilot"]
auto-format = true

[language-server.ty]
command = "sh"
args = ["-c", "mise exec ty -- ty server"]

[language-server.ty.config]
inlayHints.callArgumentNames = true
experimental.rename = true
experimental.autoImport = true

[language-server.ruff]
command = "sh"
args = ["-c", "mise exec ruff -- ruff server"]

[[language]]
name = "hcl"
language-servers = ["terraform-ls", "copilot"]
language-id = "terraform"
auto-format = true

[[language]]
name = "tfvars"
language-servers = ["terraform-ls", "copilot"]
language-id = "terraform-vars"

[language-server.terraform-ls]
command = "sh"
args = ["-c","mise exec terraform-ls -- terraform-ls serve"]
# config.indexing.ignorePaths = ["ignore.hcl"]

[language-server.sqls]
command = "sh"
args =["-c","mise exec github:sqls-server/sqls -- sqls"]

[[language]]
name = "sql"
language-servers = [ "sqls" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "oxfmt", "oxlint", "copilot"]
auto-format = true

[language-server.oxfmt]
command = "sh"
args =["-c","bunx oxfmt --lsp"]

[language-server.oxlint]
command = "sh"
args =["-c","bunx oxlint --lsp"]

[language-server.marksman]
command = "sh"
args =["-c","mise exec marksman -- marksman server"]

[[language]]
name = "markdown"
language-servers = ["marksman"]
auto-format = true

[language-server.bash-language-server]
command = "sh"
args =["-c","mise exec npm:bash-language-server -- bash-language-server start"]

[[language]]
name = "bash"
language-servers = ["bash-language-server"]
auto-format = true
