[tools]
bat = "latest"
fd = "latest"
lefthook = "latest"
jq = "latest"
starship = "latest"
delta = "latest"
typos = "latest"
rg = "latest"
zoxide = "latest"
fzf = "latest"
helix = "latest"
# gcloud = "552.0.0"
eza = "latest"
argc = "latest"
dust = "latest"
zellij = "latest"
lazygit = "latest"
ctop = "latest"
dotenvx = "latest"
yazi = "latest"
jnv = "latest"
yq = "latest"
terraform-ls = "latest"
node = "latest"
jj = "latest"
btop = "latest"
duckdb = "latest"
marksman = "latest"
rclone = "latest"
"github:tofuutils/tenv" = "latest"
"github:htop-dev/htop" = "latest"
"pipx:tldr" = "latest"
worktrunk = "latest"
"nix:pueue" = "latest" # pueuedがgithub backendからのインストールに対応していない
go = "latest"
herdr = "latest"

[settings]
experimental = true
