[tools]
bat = "latest"
fd = "latest"
lefthook = "latest"
jq = "latest"
starship = "latest"
delta = "latest"
typos = "latest"
rg = "latest"
zoxide = "latest"
fzf = "latest"
helix = "latest"
# gcloud = "552.0.0"
eza = "latest"
argc = "latest"
dust = "latest"
zellij = "latest"
lazygit = "latest"
ctop = "latest"
dotenvx = "latest"
yazi = "latest"
jnv = "latest"
yq = "latest"
terraform-ls = "latest"
node = "latest"
# jj = "latest"
btop = "latest"
duckdb = "latest"
marksman = "latest"
rclone = "latest"
"github:tofuutils/tenv" = "latest"
"github:htop-dev/htop" = "latest"
"pipx:tldr" = "latest"
worktrunk = "latest"
"aqua:Nukesor/pueue/pueue" = "latest"
"aqua:Nukesor/pueue/pueued" = "latest"
go = "latest"
herdr = "latest"
hunk = "latest"
claude = "latest"
rust = "latest"
cpz = "latest"
rmz = "latest"
"github:tarka/xcp" = "latest"
ghalint = "latest"
"aqua:suzuki-shunsuke/ghatm" = "latest"
"aqua:suzuki-shunsuke/github-comment" = "latest"

[settings]
experimental = true
